### YamlMime:Role
title: Administrator
metadata:
  title: Administrator
  description: Administrators (Administratoren) implementieren, überwachen und warten Microsoft-Lösungen, einschließlich wichtiger Dienste, in den Bereichen Computer, Speicher, Netzwerk und Sicherheit.
  ms.openlocfilehash: 720651fb55930a374b51893598e56312a98975b7
  ms.sourcegitcommit: e810ce5501e748cb92937addddb4267cde8adbc7
  ms.translationtype: MT
  ms.contentlocale: de-DE
  ms.lasthandoff: 01/26/2022
  ms.locfileid: "137778304"
uid: role.administrator
summary: >
  Administrators (Administratoren) implementieren, überwachen und warten Microsoft-Lösungen, einschließlich wichtiger Dienste, in den Bereichen Computer, Speicher, Netzwerk und Sicherheit.
subTitle: Administratoren implementieren, überwachen und warten Microsoft-Lösungen.
certificationPaths:
- title: Azure-Administrator
  linkedInKeywords: Azure administrator
  uid: certification-path.azure-administrator
  prerequisites:
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.azure-administrator
    levels:
    - intermediate
- title: Messagingadministrator für Microsoft 365
  linkedInKeywords: Microsoft 365 messaging administrator
  uid: certification-path.m365-messaging-administrator
  prerequisites:
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.m365-messaging-administrator
    levels:
    - intermediate
- title: Microsoft 365 Modern Desktop Administrator
  linkedInKeywords: Microsoft 365 modern desktop administrator
  uid: certification-path.modern-desktop
  prerequisites:
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.modern-desktop
    levels:
    - intermediate
- title: Microsoft 365-Sicherheitsadministrator
  linkedInKeywords: Microsoft 365 security administrator
  uid: certification-path.m365-security-administrator
  prerequisites:
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.m365-security-administrator
    levels:
    - intermediate
- title: Microsoft Teams-Administrator
  linkedInKeywords: Microsoft Teams administrator
  uid: certification-path.m365-teams-administrator-associate
  prerequisites:
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.m365-teams-administrator-associate
    levels:
    - intermediate
- title: Identity and Access Administrator
  linkedInKeywords: Identity and access administrator
  uid: certification-path.identity-and-access-administrator
  prerequisites:
  - uid: certification.security-compliance-and-identity-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.identity-and-access-administrator
    levels:
    - intermediate
- title: Information Protection-Administrator
  linkedInKeywords: Information protection administrator
  uid: certification-path.information-protection-administrator
  prerequisites:
  - uid: certification.security-compliance-and-identity-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.information-protection-administrator
    levels:
    - intermediate
- title: Unternehmensadministrator
  linkedInKeywords: Enterprise administrator
  uid: certification-path.m365-enterprise-administrator
  prerequisites:
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.modern-desktop
    levels:
    - intermediate
  - uid: certification.m365-security-administrator
    levels:
    - intermediate
  - uid: certification.m365-messaging-administrator
    levels:
    - intermediate
  - uid: certification.m365-teams-administrator-associate
    levels:
    - intermediate
  - uid: certification.identity-and-access-administrator
    levels:
    - intermediate
  - uid: certification.m365-enterprise-administrator
    levels:
    - advanced
- title: Azure Stack Hub-Administrator
  linkedInKeywords: Azure Stack Hub administrator
  uid: certification-path.azure-stack-hub-operator
  prerequisites:
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.azure-stack-hub-operator
    levels:
    - intermediate
- title: Microsoft Teams Voice Engineer
  linkedInKeywords: Microsoft Teams voice engineer
  uid: certification-path.m365-teams-voice-engineer-expert
  prerequisites:
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.m365-teams-administrator-associate
    levels:
    - intermediate
  - uid: certification.m365-teams-voice-engineer-expert
    levels:
    - advanced
- title: Windows Server-Hybridadministrator
  linkedInKeywords: Windows Server hybrid administrator
  uid: certification-path.windows-server-hybrid-administrator
  prerequisites:
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.windows-server-hybrid-administrator
    levels:
    - intermediate
certifications:
- uid: certification.azure-administrator
  requiredExams:
  - uid: exam.az-104
- uid: certification.azure-for-sap-workloads-specialty
  requiredExams:
  - uid: exam.az-120
- uid: certification.azure-virtual-desktop-specialty
  requiredExams:
  - uid: exam.az-140
- uid: certification.azure-stack-hub-operator
  requiredExams:
  - uid: exam.az-600
- uid: certification.m365-messaging-administrator
  requiredExams:
  - uid: exam.ms-203
- uid: certification.modern-desktop
  requiredExams:
  - uid: exam.md-100
  - uid: exam.md-101
- uid: certification.m365-security-administrator
  requiredExams:
  - uid: exam.ms-500
- uid: certification.m365-enterprise-administrator
  requiredExams:
  - uid: exam.ms-100
  - uid: exam.ms-101
- uid: certification.m365-teams-administrator-associate
  requiredExams:
  - uid: exam.ms-700
- uid: certification.identity-and-access-administrator
  requiredExams:
  - uid: exam.sc-300
- uid: certification.information-protection-administrator
  requiredExams:
  - uid: exam.sc-400
- uid: certification.m365-teams-voice-engineer-expert
  requiredExams:
  - uid: exam.ms-720
- uid: certification.windows-server-hybrid-administrator
  requiredExams:
  - uid: exam.az-800
  - uid: exam.az-801
resources:
- title: Microsoft Leitfaden für Schulungen und Zertifizierungen
  description: Informieren Sie sich über die Zertifizierungen in einem übersichtlichen Schulungs- und Zertifizierungsleitfaden.
  href: https://aka.ms/TrainingCertDeck
- title: Poster für Schulungen und Zertifizierungen
  description: Wählen Sie mit diesem Poster für Schulungen und Zertifizierungen Ihren Weg zum Erfolg.
  href: https://aka.ms/traincertposter
- title: Unterstützung von Zertifizierungen
  href: ../help.md
  description: Erhalten Sie Hilfe in Microsoft Certification Support-Foren. Ein Forenmoderator wird Ihnen an einem Werktag (Montag-Freitag) antworten.
