### YamlMime:Role
title: Data Scientist
metadata:
  title: Data Scientist
  description: Data Scientists (Datenwissenschaftler) wenden Methoden des maschinellen Lernens an, um Modelle zur Lösung von Geschäftsproblemen zu entwickeln, zu bewerten und einzusetzen.
  ms.openlocfilehash: bcc5e02ef053cf66b85a97f5506c4f9311bf1ea6
  ms.sourcegitcommit: 15832c0b302b429735730b73fbfd30bb4b3f0771
  ms.translationtype: MT
  ms.contentlocale: de-DE
  ms.lasthandoff: 01/04/2022
  ms.locfileid: "135763432"
uid: role.data-scientist
summary: >
  Data Scientists (Datenwissenschaftler) wenden Methoden des maschinellen Lernens an, um Modelle zur Lösung von Geschäftsproblemen zu entwickeln, zu bewerten und einzusetzen.
subTitle: Data Scientists (Datenwissenschaftler) wenden Methoden des maschinellen Lernens an, um Modelle zur Lösung von Geschäftsproblemen zu entwickeln, zu bewerten und einzusetzen.
certificationPaths:
- title: Azure-Datenwissenschaftler
  linkedInKeywords: Azure data scientist
  uid: certification-path.azure-data-scientist
  prerequisites:
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.azure-data-scientist
    levels:
    - intermediate
certifications:
- uid: certification.azure-data-scientist
  requiredExams:
  - uid: exam.dp-100
- uid: certification.customer-data-platform-specialty
  requiredExams:
  - uid: exam.mb-260
resources:
- title: Microsoft Leitfaden für Schulungen und Zertifizierungen
  description: Informieren Sie sich über die Zertifizierungen in einem übersichtlichen Schulungs- und Zertifizierungsleitfaden.
  href: https://aka.ms/TrainingCertDeck
- title: Poster für Schulungen und Zertifizierungen
  description: Wählen Sie mit diesem Poster für Schulungen und Zertifizierungen Ihren Weg zum Erfolg.
  href: https://aka.ms/traincertposter
- title: Unterstützung von Zertifizierungen
  href: ../help.md
  description: Erhalten Sie Hilfe in Microsoft Certification Support-Foren. Ein Forenmoderator wird Ihnen an einem Werktag (Montag-Freitag) antworten.
