### YamlMime:Role
title: Entwickler
metadata:
  title: Entwickler
  description: Developers (Entwickler) entwerfen, erstellen, testen und warten Lösungen. Developers (Entwickler) implementieren Anwendungen und Dienste in Zusammenarbeit mit Solution Architects (Lösungsarchitekten) und Kunden.
  ms.openlocfilehash: 3e721bab06b6d102f72dc9555c2433d03e89c5b6
  ms.sourcegitcommit: b69fd4d0c808e4780010278f0cb189c2246f8dc0
  ms.translationtype: MT
  ms.contentlocale: de-DE
  ms.lasthandoff: 12/28/2021
  ms.locfileid: "133301834"
uid: role.developer
summary: "Developers (Entwickler) entwerfen, erstellen, testen und warten Lösungen. Developers (Entwickler) implementieren Anwendungen und Dienste in Zusammenarbeit mit Solution Architects (Lösungsarchitekten) und Kunden. \n"
subTitle: Developers (Entwickler) entwerfen, erstellen, testen und warten Cloud-Lösungen.
certificationPaths:
- title: Azure-Entwickler
  linkedInKeywords: Azure developer
  uid: certification-path.developer
  prerequisites:
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.azure-developer
    levels:
    - intermediate
- title: Dynamics 365 Finance and Operations Apps Developer
  linkedInKeywords: Dynamics 365 finance and operations apps developer
  uid: certification-path.d365-finance-and-operations-apps-developer-associate
  prerequisites:
  - uid: certification.d365-fundamentals-customer-engagement-apps-crm
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-finance-and-operations-apps-developer-associate
    levels:
    - intermediate
- title: Microsoft 365-Entwickler
  linkedInKeywords: Microsoft 365 developer
  uid: certification-path.m365-developer-associate
  prerequisites:
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.m365-developer-associate
    levels:
    - intermediate
- title: Power Platform Developer
  linkedInKeywords: Power Platform developer
  uid: certification-path.power-platform-developer-associate
  prerequisites:
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.power-platform-developer-associate
    levels:
    - intermediate
certifications:
- uid: certification.azure-developer
  requiredExams:
  - uid: exam.az-204
- uid: certification.d365-finance-and-operations-apps-developer-associate
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-500
- uid: certification.m365-developer-associate
  requiredExams:
  - uid: exam.ms-600
- uid: certification.power-platform-developer-associate
  requiredExams:
  - uid: exam.pl-400
- uid: certification.azure-iot-developer-specialty
  requiredExams:
  - uid: exam.az-220
- uid: certification.azure-cosmos-db-developer-specialty
  requiredExams:
  - uid: exam.dp-420
resources:
- title: Microsoft Leitfaden für Schulungen und Zertifizierungen
  description: Informieren Sie sich über die Zertifizierungen in einem übersichtlichen Schulungs- und Zertifizierungsleitfaden.
  href: https://aka.ms/TrainingCertDeck
- title: Poster für Schulungen und Zertifizierungen
  description: Wählen Sie mit diesem Poster für Schulungen und Zertifizierungen Ihren Weg zum Erfolg.
  href: https://aka.ms/traincertposter
- title: Unterstützung von Zertifizierungen
  href: ../help.md
  description: Erhalten Sie Hilfe in Microsoft Certification Support-Foren. Ein Forenmoderator wird Ihnen an einem Werktag (Montag-Freitag) antworten.
