### YamlMime:Role 
title: Developer 
metadata: 
  title: Developer 
  description: Developers (Entwickler) entwerfen, erstellen, testen und warten Lösungen. Developers (Entwickler) implementieren Anwendungen und Services in Zusammenarbeit mit Solution Architects (Lösungsarchitekten) und Kunden.
uid: role.developer 
summary: | 
  Developers (Entwickler) entwerfen, erstellen, testen und warten Lösungen. Developers (Entwickler) implementieren Anwendungen und Services in Zusammenarbeit mit Solution Architects (Lösungsarchitekten) und Kunden. 
subTitle: Developers (Entwickler) entwerfen, erstellen, testen und warten Cloud-Lösungen.
certificationPaths: 
- title: Azure Developer
  linkedInKeywords: Azure Developer
  uid: certification-path.developer 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-developer
    levels:
    - intermediate 
- title: Dynamics 365 Finance and Operations Apps Developer
  linkedInKeywords: Dynamics 365 Finance and Operations Apps Developer
  uid: certification-path.d365-finance-and-operations-apps-developer-associate
  prerequisites: 
  - uid: certification.d365-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-finance-and-operations-apps-developer-associate
    levels:
    - intermediate
- title: Microsoft 365 Developer
  linkedInKeywords: Microsoft 365 Developer
  uid: certification-path.m365-developer-associate
  prerequisites:
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.m365-developer-associate
    levels:
    - intermediate
- title: Power Platform Developer
  linkedInKeywords: Power Platform Developer
  uid: certification-path.power-platform-developer-associate
  prerequisites:
  - uid: certification.power-platform-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.power-platform-developer-associate
    levels:
    - intermediate
certifications:
- uid: certification.azure-developer
  requiredExams:
  - uid: exam.az-204
- uid: certification.d365-finance-and-operations-apps-developer-associate
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-500
- uid: certification.m365-developer-associate
  requiredExams:
  - uid: exam.ms-600
- uid: certification.power-platform-developer-associate
  requiredExams:
  - uid: exam.pl-400
- uid: certification.azure-iot-developer-specialty
  requiredExams:
  - uid: exam.az-220
resources:
- title: Microsoft Leitfaden für Schulungen und Zertifizierungen
  description: Informieren Sie sich über die Zertifizierungen in einem übersichtlichen Schulungs- und Zertifizierungsleitfaden.
  href: https://aka.ms/TrainingCertDeck
- title: Poster für Schulungen und Zertifizierungen
  description: Wählen Sie mit diesem Poster für Schulungen und Zertifizierungen Ihren Weg zum Erfolg.
  href: https://aka.ms/traincertposter
- title: Unterstützung von Zertifizierungen
  href: ../help.md
  description: Erhalten Sie Hilfe in Microsoft Certification Support-Foren. Ein Forenmoderator wird Ihnen an einem Werktag (Montag-Freitag) antworten.
