### YamlMime:Role
title: Functional Consultant
metadata:
  title: Functional Consultant
  description: Functional Consultants (Funktionsberater) nutzen Microsoft Dynamics 365 und Microsoft Power Platform, um Kundenbedürfnisse zu antizipieren und zu planen.
  ms.openlocfilehash: b34e4ee923d360f8da041733ede93d59762a83cd
  ms.sourcegitcommit: 9910ee6c567f78305da1d27159bd03c6f3258035
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 11/24/2021
  ms.locfileid: "133079095"
uid: role.functional-consultant
summary: >
  Functional Consultants (Funktionsberater) nutzen Microsoft Dynamics 365 und Microsoft Power Platform, um Kundenbedürfnisse zu antizipieren und zu planen.
subTitle: Functional Consultants (Funktionsberater) nutzen Microsoft Dynamics 365 und Microsoft Power Platform, um Kundenbedürfnisse zu antizipieren und zu planen.
certificationPaths:
- title: Dynamics 365 Customer Service Functional Consultant
  linkedInKeywords: Dynamics 365 Customer Service functional consultant
  uid: certification-path.d365-functional-consultant-customer-service
  prerequisites:
  - uid: certification.d365-fundamentals-customer-engagement-apps-crm
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-customer-service
    levels:
    - intermediate
- title: Dynamics 365 Field Service Functional Consultant
  linkedInKeywords: Dynamics 365 Field Service functional consultant
  uid: certification-path.d365-functional-consultant-field-service
  prerequisites:
  - uid: certification.d365-fundamentals-customer-engagement-apps-crm
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-field-service
    levels:
    - intermediate
- title: Dynamics 365 Finance Functional Consultant
  linkedInKeywords: Dynamics 365 Finance functional consultant
  uid: certification-path.d365-functional-consultant-financials
  prerequisites:
  - uid: certification.d365-fundamentals-finance-and-operations-apps-erp
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-financials
    levels:
    - intermediate
- title: Dynamics 365 Manufacturing Functional Consultant
  linkedInKeywords: Dynamics 365 Manufacturing functional consultant
  uid: certification-path.d365-functional-consultant-manufacturing
  prerequisites:
  - uid: certification.d365-fundamentals-finance-and-operations-apps-erp
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-manufacturing
    levels:
    - intermediate
- title: Dynamics 365 Marketing Functional Consultant
  linkedInKeywords: Dynamics 365 Marketing functional consultant
  uid: certification-path.d365-functional-consultant-marketing
  prerequisites:
  - uid: certification.d365-fundamentals-customer-engagement-apps-crm
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-marketing
    levels:
    - intermediate
- title: Dynamics 365 Sales Functional Consultant
  linkedInKeywords: Dynamics 365 Sales functional consultant
  uid: certification-path.d365-functional-consultant-sales
  prerequisites:
  - uid: certification.d365-fundamentals-customer-engagement-apps-crm
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-sales
    levels:
    - intermediate
- title: Dynamics 365 Supply Chain Management Functional Consultant
  linkedInKeywords: Dynamics 365 Supply Chain Management functional consultant
  uid: certification-path.d365-functional-consultant-supply-chain-management
  prerequisites:
  - uid: certification.d365-fundamentals-finance-and-operations-apps-erp
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-functional-consultant-supply-chain-management
    levels:
    - intermediate
- title: Functional Consultant für Power Platform
  linkedInKeywords: Power Platform functional consultant
  uid: certification-path.power-platform-functional-consultant-associate
  prerequisites:
  - uid: certification.d365-fundamentals-finance-and-operations-apps-erp
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-fundamentals-customer-engagement-apps-crm
    isOptional: true
    levels:
    - beginner
  - uid: certification.power-platform-functional-consultant-associate
    levels:
    - intermediate
- title: Functional Consultant für Dynamics 365 Business Central
  linkedInKeywords: Dynamics 365 Business Central functional consultant
  uid: certification-path.d365-business-central-functional-consultant-associate
  prerequisites:
  - uid: certification.d365-fundamentals-finance-and-operations-apps-erp
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-fundamentals-customer-engagement-apps-crm
    isOptional: true
    levels:
    - beginner
  - uid: certification.d365-business-central-functional-consultant-associate
    levels:
    - intermediate
certifications:
- uid: certification.d365-functional-consultant-customer-service
  requiredExams:
  - uid: exam.pl-200
  - uid: exam.mb-230
- uid: certification.d365-functional-consultant-field-service
  requiredExams:
  - uid: exam.pl-200
  - uid: exam.mb-240
- uid: certification.d365-functional-consultant-financials
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-310
- uid: certification.d365-functional-consultant-manufacturing
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-320
- uid: certification.d365-functional-consultant-marketing
  requiredExams:
  - uid: exam.pl-200
  - uid: exam.mb-220
- uid: certification.d365-functional-consultant-sales
  requiredExams:
  - uid: exam.pl-200
  - uid: exam.mb-210
- uid: certification.d365-functional-consultant-supply-chain-management
  requiredExams:
  - uid: exam.mb-300
  - uid: exam.mb-330
- uid: certification.power-platform-functional-consultant-associate
  requiredExams:
  - uid: exam.pl-200
- uid: certification.d365-business-central-functional-consultant-associate
  requiredExams:
  - uid: exam.mb-800
resources:
- title: Microsoft Leitfaden für Schulungen und Zertifizierungen
  description: Informieren Sie sich über die Zertifizierungen in einem übersichtlichen Schulungs- und Zertifizierungsleitfaden.
  href: https://aka.ms/TrainingCertDeck
- title: Poster für Schulungen und Zertifizierungen
  description: Wählen Sie mit diesem Poster für Schulungen und Zertifizierungen Ihren Weg zum Erfolg.
  href: https://aka.ms/traincertposter
- title: Unterstützung von Zertifizierungen
  href: ../help.md
  description: Erhalten Sie Hilfe in Microsoft Certification Support-Foren. Ein Forenmoderator wird Ihnen an einem Werktag (Montag-Freitag) antworten.
