### YamlMime:Role
title: Security Engineer
metadata:
  title: Security Engineer
  description: Security Engineers (Sicherheitstechniker) implementieren Sicherheitskontrollen und Bedrohungsschutz, verwalten Identitäten und Zugriffe und schützen Daten, Anwendungen und Netzwerke.
  ms.openlocfilehash: 23f9035bc8bcd035f88593c52e761ad49929b6f7
  ms.sourcegitcommit: b69fd4d0c808e4780010278f0cb189c2246f8dc0
  ms.translationtype: MT
  ms.contentlocale: de-DE
  ms.lasthandoff: 12/28/2021
  ms.locfileid: "133989061"
uid: role.security-engineer
summary: >
  Security Engineers (Sicherheitstechniker) implementieren Sicherheitskontrollen und Bedrohungsschutz, verwalten Identitäten und Zugriffe und schützen Daten, Anwendungen und Netzwerke.
subTitle: Security Engineers (Sicherheitstechniker) implementieren Sicherheitskontrollen und Bedrohungsschutz, verwalten Identitäten und Zugriffe und schützen Daten, Anwendungen und Netzwerke.
certificationPaths:
- title: Azure Security Engineer
  linkedInKeywords: Azure security engineer
  uid: certification-path.azure-security-engineer
  prerequisites:
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.azure-security-engineer
    levels:
    - intermediate
- title: Identity and Access Administrator
  linkedInKeywords: Identity and access administrator
  uid: certification-path.identity-and-access-administrator
  prerequisites:
  - uid: certification.security-compliance-and-identity-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.identity-and-access-administrator
    levels:
    - intermediate
- title: Information Protection-Administrator
  linkedInKeywords: Information protection administrator
  uid: certification-path.information-protection-administrator
  prerequisites:
  - uid: certification.security-compliance-and-identity-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.information-protection-administrator
    levels:
    - intermediate
- title: Security Operations Analyst
  linkedInKeywords: Security operations analyst
  uid: certification-path.security-operations-analyst
  prerequisites:
  - uid: certification.security-compliance-and-identity-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.security-operations-analyst
    levels:
    - intermediate
- title: Windows Server-Hybridadministrator
  linkedInKeywords: Windows Server hybrid administrator
  uid: certification-path.windows-server-hybrid-administrator
  prerequisites:
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner
  - uid: certification.windows-server-hybrid-administrator
    levels:
    - intermediate
certifications:
- uid: certification.azure-security-engineer
  requiredExams:
  - uid: exam.az-500
- uid: certification.security-operations-analyst
  requiredExams:
  - uid: exam.sc-200
- uid: certification.identity-and-access-administrator
  requiredExams:
  - uid: exam.sc-300
- uid: certification.information-protection-administrator
  requiredExams:
  - uid: exam.sc-400
- uid: certification.windows-server-hybrid-administrator
  requiredExams:
  - uid: exam.az-800
  - uid: exam.az-801
resources:
- title: Microsoft Leitfaden für Schulungen und Zertifizierungen
  description: Informieren Sie sich über die Zertifizierungen in einem übersichtlichen Schulungs- und Zertifizierungsleitfaden.
  href: https://aka.ms/TrainingCertDeck
- title: Poster für Schulungen und Zertifizierungen
  description: Wählen Sie mit diesem Poster für Schulungen und Zertifizierungen Ihren Weg zum Erfolg.
  href: https://aka.ms/traincertposter
- title: Unterstützung von Zertifizierungen
  href: ../help.md
  description: Erhalten Sie Hilfe in Microsoft Certification Support-Foren. Ein Forenmoderator wird Ihnen an einem Werktag (Montag-Freitag) antworten.
