### YamlMime:FAQ
metadata:
  title: 'FAQ: Learning Partner-Kursplanung auf Learn | Microsoft Docs'
  description: 'FAQ: Learning Partner-Kursplanung auf Learn'
  documentationcenter: NA 
  author: micsullivan
  ms.topic: article
  ms.tgt_pltfrm: NA
  ms.workload: NA
  ms.date: 09/01/2020
  ms.author: msulliv
  ms.prod: non-product-specific
    
title: 'FAQ: Learning Partner-Kursplanung auf Learn'
summary: |

## Ausbilder-geführte Ausbildung

sections:
  - name: Ausbilder-geführte Ausbildung
    questions:
      - question: |
          Was ist der von Microsoft Learning Partner geleitete Schulungsplanungsdienst?
        answer: |
          Microsoft bietet eine vereinfachte und gestraffte Lernerfahrung, indem es [Microsoft Learn](/learn) mit Echtzeit-Schulungsplanungsfunktionen unter Anleitung ausstattet. Die Integration des Kurszeitplans in Microsoft Learn ermöglicht es den Lernenden, eine Vorschau der von qualifizierten Lernpartnern angebotenen, von Ausbildern geleiteten Schulungskurse anzuzeigen. Sobald ein Kurs ausgewählt wurde, werden Sie direkt zur Lernpartner-Website weitergeleitet, um die Anmeldung und Bezahlung abzuschließen.
          
          Dieser Dienst ist derzeit die 'Public Preview' und die Kursregistrierung wird zu Beginn nur auf Englisch verfügbar sein. Weitere qualifizierte Lernpartner werden im Laufe des nächsten Jahres hinzugefügt.
          
      - question: |
          Welche Kurse sind mit dem von Learning Partner-Lehrern geleiteten Schulungsplanungsservice verfügbar?
        answer: |
          Ab 22. September 2020 sind die folgenden Kurse mit dem Planungsservice verfügbar. Zusätzliche Kurse werden im Laufe der Zeit hinzugefügt, wenn wir zusätzliche Lernpartner hinzufügen.
          
          1. Microsoft Azure Fundamentals (2 day)
          2. Microsoft Azure Fundamentals (1 day)
          3. Microsoft Azure Administrator
          4. Developing Solutions for Microsoft Azure
          5. Designing and Implementing an Azure AI Solution
          6. Designing and Implementing a Data Science Solution on Azure
          7. Designing an Azure Data Solution
          8. Implementing an Azure Data Solution
          9. Designing for Identity and Security
          10. Deploying and Configuring Infrastructure
          11. Microsoft Azure Architect Design
          12. Microsoft Azure Security Technologies
          13. Installing Windows 10
          14. Dynamics 365: Power Platform Applications
          15. Office 365 Management
          16. Managing Microsoft 365 Identity and Access
          17. Microsoft 365 Fundamentals
          
      - question: |
          Muss ich ein Profil erstellen, um Microsoft Learn nutzen zu können?earn?
        answer: |
          Nein, die Erstellung eines Profils ist nicht erforderlich. Sie können weiterhin auf Online-Lehrpfade zugreifen und diese nutzen, [Durchsuchen Sie Kurse mit Kursleitern](/learn/certifications/courses/browse/), und [Finden Sie einen Microsoft Learning Partner im jeweiligen Land](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country) without needing to create a profile.
          
          Wenn Sie einen von einem Ausbilder geleiteten Schulungskurs zu Microsoft Learn planen, werden Sie zur Website des ausgewählten Lernpartners weitergeleitet, um die Anmeldung und Bezahlung abzuschließen. Lernpartner können verlangen, dass Sie sich auf ihrer Website anmelde
          
      - question: |
          Welche Funktionen stehen mir zur Verfügung, wenn ich ein Microsoft Learn-Profil erstelle und mich anmelde?
        answer: |
          - Fortschritte bei Lernaktivitäten verfolgen
          - Sammlungen von Modulen erstellen und gemeinsam nutzen
          - Lesezeichen speichern
          - Punkte und Leistungen sammeln
          - Nutzen Sie kostenlose Azure-Ressourcen
          - Personalisierte Empfehlungen anzeigen 
          
      - question: |
          Ich habe mich für einen Kurs bei einem Lernpartner für Microsoft Learn angemeldet und keine Kursbestätigung erhalten. Was soll ich tun?
        answer: |
          Bitte überprüfen Sie Ihren Posteingang, Junk-E-Mail oder Spam auf der Suche nach einer E-Mail des Lernpartners für den Kurs, für den Sie sich angemeldet haben.  
          
          Wenn Sie Ihre Bestätigungsmail immer noch nicht finden können, wenden Sie sich an den Lernpartner, bei dem Sie den Kurs geplant haben. Der Lernpartner kann bei der Behebung von E-Mail-Problemen helfen und/oder die Kursanmeldung überprüfen. Die Kontaktinformationen des Lernpartners finden Sie unter [Finden Sie einen Microsoft Learning Partner im jeweiligen Land](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country)
          
      - question: |
          Ich melde mich für einen Kurs an und habe die Website des Lernpartners erreicht, aber es befindet sich nichts im Warenkorb.   
        answer: |
          Bitte wenden Sie sich an den Learning Provider, den Sie für den Kurs ausgewählt haben, um das Problem zu lösen. Die Kontaktinformationen des Lernpartners finden Sie unter [Finden Sie einen Microsoft Learning Partner im jeweiligen Land](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country)
          
      - question: |
          Ich muss einen Kurs stornieren oder neu planen.  
        answer: |
          Bitte wenden Sie sich direkt an den Lernpartner. Die Kontaktinformationen des Lernpartners finden Sie unter [Finden Sie einen Microsoft Learning Partner im jeweiligen Land](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country)
          
      - question: |
          Der auf der Website des Lernpartners angegebene Preis war nicht derselbe wie der an der Kasse angegebene. 
        answer: |
          Der Preis auf der Website oder im Warenkorb des Lernpartners sollte immer als Preis für den Artikel verwendet werden, auch wenn Learn einen anderen Betrag ausweist.

          Es ist möglich, dass der Endpreis auf der Lernpartner-Website oder im Warenkorb anders ausfällt, da möglicherweise Steuern enthalten sind oder Steuern, die während des Bestellvorgangs berechnet werden müssen. Dies kann Verkaufssteuer und Mehrwertsteuer (VAT) einschließen. Der von Ihnen zu zahlende Endbetrag kann auch durch den Standort des Käufers oder die Sprache des Kurses beeinflusst werden.

          Einige Lernpartner bieten während des Bestellvorgangs möglicherweise zusätzliche Service-Add-ons an. Der Preis dieser Dienstleistungen kann den Endpreis, den Sie an der Kasse sehen, ändern.   
          
      - question: |
          Wann werde ich Kurse in meinem Land oder meiner Region sehen?  
        answer: |
          Dies ist ein neuer Dienst, der in der ‚Public Preview' mit einer kleinen Anzahl qualifizierter Lernpartner veröffentlicht wurde, um die Funktionalität zu testen und den Prozess fein abzustimmen. Zunächst wird die Kursplanung auf Englisch erfolgen, weitere Lernpartner werden im Laufe der nächsten 12 Monate hinzukommen.

      - question: |
          Wie kommt es, dass andere Schulungskurse mehr oder weniger kosten als derjenige, den ich besuchen möchte?
        answer: |
          Wie bei jedem Marktplatz wird der Preis des Kurses von jedem Lernpartner festgelegt. Die Partner müssen eine vollständige Microsoft Official Course-Schulung zu dem Preis anbieten, der auf dem Microsoft Learn-Tool für die Terminplanung angegeben ist. Es ist den Partnern gestattet, zusätzliche Produkte und Dienstleistungen zu bewerben, die optional sind. Wenn Sie der Meinung sind, dass die angezeigten Preise irreführend oder ungenau sind, wenden Sie sich bitte an das [Learning Partner instructor-led course scheduling on Learn support forum](https://trainingsupport.microsoft.com/en-us/iltvilt/forum).
          
      - question: |
          Die Filterung nach Kursort, Datum usw. funktioniert nicht richtig.
        answer: |
          Wenn die Filterung nicht funktioniert, aktualisieren Sie bitte Ihren Browser und versuchen Sie es erneut. Wenn Sie der Meinung sind, dass die Filter immer noch nicht funktionieren, können Sie Ihre Frage im [Lernpartner: von einem Ausbilder geleitete Kursplanung im Supportforum Lernen](https://trainingsupport.microsoft.com/en-us/iltvilt/forum). Dies ist die beste Ressource, um zu suchen und um Hilfe zu bitten, ein Problem zu melden und Ratschläge zu erhalten.
          
      - question: |
          Ich kann den Lernpartner in meinem Gebiet nicht finden.
        answer: |
          Wenn Sie den gesuchten Lernpartner oder Kurs nicht finden können, finden Sie möglicherweise zusätzliche Tage und Uhrzeiten direkt auf einer Lernpartner-Website, die über die Anzeige auf Microsoft Learn hinausgehen.  Lernpartner sind nicht verpflichtet, Zeitpläne für alle ihre Kurse aufzulisten. Eine Liste aller Microsoft Learning Partner finden Sie unter [Microsoft Learning Partner nach Land oder Region suchen](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country).

          Mit der Einführung dieses neuen Dienstes begrenzen wir die Anzahl der qualifizierten Lernpartner. Im Laufe des nächsten Jahres werden Lernpartner hinzugefügt, die bestimmte Kriterien erfüllen.
          
      - question: |
          Ich habe den Supportkanal des Lernpartners durchlaufen und keine Antwort erhalten.
        answer: |
          Der Lernpartner ist für die Unterstützung bei der Terminplanung auf seiner Website verantwortlich. Sie können verschiedene Nummern für den Lernpartner ausprobieren, indem Sie sich seine Website ansehen.

          Wenn Sie den Lernpartner immer noch nicht erreichen können, können Sie Ihre Frage im [Lernpartner: von Ausbildern geleitete Kursplanung im Supportforum für Lernende](https://trainingsupport.microsoft.com/en-us/iltvilt/forum) stellen. Dies ist die beste Ressource, um Hilfe zu bitten, ein Problem zu melden und Rat zu erhalten.
