### YamlMime:FAQ
metadata:
  title: 'FAQ: Learning Partner-Kursplanung auf Learn | Microsoft-Dokumentation'
  description: 'FAQ: Learning Partner-Kursplanung auf Learn'
  documentationcenter: NA
  author: micsullivan
  ms.topic: article
  ms.tgt_pltfrm: NA
  ms.workload: NA
  ms.date: 09/01/2020
  ms.author: msulliv
  ms.prod: non-product-specific
  ms.openlocfilehash: f699b9754540f502f4b0dce9f4dc3b9a5ff2f733
  ms.sourcegitcommit: b69fd4d0c808e4780010278f0cb189c2246f8dc0
  ms.translationtype: MT
  ms.contentlocale: de-DE
  ms.lasthandoff: 12/28/2021
  ms.locfileid: "132111509"
title: 'FAQ: Learning Partner-Kursplanung auf Learn'
summary: "\n## <a name=\"instructor-led-training\"></a>Präsenzschulung\n"
sections:
- name: Präsenzschulung
  questions:
  - question: >
      Was ist der Planungsdienst für Präsenzschulungen von Microsoft Learning-Partnern?
    answer: "Microsoft bietet eine vereinfachte und gestraffte Lernumgebung durch die Integration von Terminplanungsfunktionen für Präsenzschulungen in [**Microsoft Learn**](/learn). Die Integration des Kurszeitplans in Microsoft Learn ermöglicht es den Lernenden, eine Vorschau der von qualifizierten Lernpartnern angebotenen, von Ausbildern geleiteten Schulungskurse anzuzeigen. Sobald ein Kurs ausgewählt wurde, werden Sie direkt zur Lernpartner-Website weitergeleitet, um die Anmeldung und Bezahlung abzuschließen.\n\nDieser Dienst ist derzeit die 'Public Preview' und die Kursregistrierung wird zu Beginn nur auf Englisch verfügbar sein. Weitere qualifizierte Lernpartner werden im Laufe des nächsten Jahres hinzugefügt. \n"
  - question: >
      Welche Kurse sind mit dem Planungsdienst für Präsenzschulungen von Learning-Partnern verfügbar?
    answer: >
      Ab dem 22. September 2020 sind die folgenden Kurse mit dem Planungsdienst verfügbar. Weitere Kurse werden im Laufe der Zeit verfügbar, wenn wir zusätzliche Learning-Partner hinzufügen.


      1. Grundlagen zu Microsoft Azure (2 Tage)

      2. Grundlagen zu Microsoft Azure (1 Tag)

      3. Microsoft Azure-Administrator

      4. Developing Solutions for Microsoft Azure

      5. Entwerfen und Implementieren einer Azure AI Lösung

      6. Entwerfen und Implementieren einer Data Science-Lösung in Azure

      7. Entwerfen einer Azure-Datenlösung

      8. Implementierung einer Azure-Datenlösung

      9. Designing for Identity and Security

      10. Deploying and Configuring Infrastructure

      11. Microsoft Azure Architect Design

      12. Microsoft Azure-Sicherheitstechnologien

      13. Installieren von Windows 10

      14. Dynamics 365: Power Platform-Anwendungen

      15. Office 365 Management

      16. Verwalten von Microsoft 365-Identitäten and -Zugriff

      17. Grundlagen zu Microsoft 365
  - question: >
      Muss ich ein Profil erstellen, um Microsoft Learn zu verwenden?
    answer: >
      Nein, Sie müssen kein Profil erstellen. Sie können weiterhin auf Onlinelernpfade zugreifen und diese nutzen, [Präsenzschulungen durchsuchen](/learn/certifications/courses/browse/) und einen [Microsoft Learning-Partner nach Land oder Region suchen](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country), ohne ein Profil erstellen zu müssen.


      Wenn Sie einen von einem Ausbilder geleiteten Schulungskurs zu Microsoft Learn planen, werden Sie zur Website des ausgewählten Lernpartners weitergeleitet, um die Anmeldung und Bezahlung abzuschließen. Lernpartner können verlangen, dass Sie sich auf ihrer Website anmelden.
  - question: >
      Welche Funktionen stehen mir zur Verfügung, wenn ich ein Microsoft Learn-Profil erstelle und mich anmelde?
    answer: "- Fortschritt bei Lernaktivitäten verfolgen \n- Modulsammlungen erstellen und teilen \n- Lesezeichen speichern \n- Punkte und Erfolge sammeln \n- Kostenlose Azure-Ressourcen nutzen \n- Personalisierte Empfehlungen anzeigen \n"
  - question: "Ich habe mich für einen Kurs bei einem Learning-Partner auf Microsoft Learn angemeldet und keine Kursbestätigung erhalten. Wie sollte ich vorgehen? \n"
    answer: "Bitte überprüfen Sie Ihren Posteingang, Junk-E-Mail oder Spam auf der Suche nach einer E-Mail des Lernpartners für den Kurs, für den Sie sich angemeldet haben.  \n\nWenn Sie Ihre Bestätigungsmail immer noch nicht finden können, wenden Sie sich an den Lernpartner, bei dem Sie den Kurs geplant haben. Der Lernpartner kann bei der Behebung von E-Mail-Problemen helfen und/oder die Kursanmeldung überprüfen. Kontaktinformationen von Learning-Partnern finden Sie unter [Suchen eines Microsoft Learning-Partners nach Land oder Region](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country).\n"
  - question: "Ich registriere mich für einen Kurs und habe die Website des Learning-Partners aufgerufen, aber es befindet sich nichts im Warenkorb.   \n"
    answer: >
      Bitte wenden Sie sich an den Learning Provider, den Sie für den Kurs ausgewählt haben, um das Problem zu lösen. Kontaktinformationen von Learning-Partnern finden Sie unter [Suchen eines Microsoft Learning-Partners nach Land oder Region](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country).
  - question: "Ich muss einen Kurs absagen oder verschieben.   \n"
    answer: >
      Bitte wenden Sie sich direkt an den Lernpartner. Kontaktinformationen von Learning-Partnern finden Sie unter [Suchen eines Microsoft Learning-Partners nach Land oder Region](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country).
  - question: "Der auf der Learn-Website angegebene Preis stimmte nicht mit dem an der Kasse überein. \n"
    answer: "Der Preis auf der Website oder im Warenkorb des Lernpartners sollte immer als Preis für den Artikel verwendet werden, auch wenn Learn einen anderen Betrag ausweist.  \n\nEs ist möglich, dass der Endpreis auf der Lernpartner-Website oder im Warenkorb anders ausfällt, da möglicherweise Steuern enthalten sind oder Steuern, die während des Bestellvorgangs berechnet werden müssen. Dies kann Verkaufssteuer und Mehrwertsteuer (VAT) einschließen. Der von Ihnen zu zahlende Endbetrag kann auch durch den Standort des Käufers oder die Sprache des Kurses beeinflusst werden.  \n\nEinige Lernpartner bieten während des Bestellvorgangs möglicherweise zusätzliche Service-Add-ons an. Der Preis dieser Dienstleistungen kann den Endpreis, den Sie an der Kasse sehen, ändern.   \n"
  - question: "Wann werden mir Kurse in meinem Land oder meiner Region angezeigt?  \n"
    answer: >
      Dies ist ein neuer Dienst, der in der ‚Public Preview' mit einer kleinen Anzahl qualifizierter Lernpartner veröffentlicht wurde, um die Funktionalität zu testen und den Prozess fein abzustimmen. Zunächst wird die Kursplanung auf Englisch erfolgen, weitere Lernpartner werden im Laufe der nächsten 12 Monate hinzukommen.
  - question: >
      Wie kommt es, dass andere Schulungskurse mehr oder weniger kosten als derjenige, den ich besuchen möchte?
    answer: >
      Wie bei jedem Marktplatz wird der Preis des Kurses von jedem Lernpartner festgelegt. Die Partner müssen eine vollständige Microsoft Official Course-Schulung zu dem Preis anbieten, der auf dem Microsoft Learn-Tool für die Terminplanung angegeben ist. Es ist den Partnern gestattet, zusätzliche Produkte und Dienstleistungen zu bewerben, die optional sind. Wenn Sie der Meinung sind, dass die beworbenen Preise irreführend oder ungenau sind, wenden Sie sich an das [Learn-Supportforum zu Präsenzschulungen von Learning-Partnern](https://trainingsupport.microsoft.com/en-us/iltvilt/forum).
  - question: >
      Die Filterung nach Kursort, Datum usw. funktioniert nicht richtig.
    answer: >
      Wenn die Filterung nicht funktioniert, aktualisieren Sie bitte Ihren Browser und versuchen Sie es erneut. Wenn die Filter noch immer nicht funktionieren, können Sie Ihre Frage im [Learn-Supportforum zu Präsenzschulungen von Learning-Partnern](https://trainingsupport.microsoft.com/en-us/iltvilt/forum) stellen. Dies ist die beste Ressource, um zu suchen und um Hilfe zu bitten, ein Problem zu melden und Ratschläge zu erhalten.
  - question: >
      Ich kann den Learning-Partner in meinem Gebiet nicht finden.
    answer: >
      Wenn Sie den gesuchten Lernpartner oder Kurs nicht finden können, finden Sie möglicherweise zusätzliche Tage und Uhrzeiten direkt auf einer Lernpartner-Website, die über die Anzeige auf Microsoft Learn hinausgehen.  Lernpartner sind nicht verpflichtet, Zeitpläne für alle ihre Kurse aufzulisten. Eine Liste aller Microsoft Learning-Partner finden Sie unter [Suchen eines Microsoft Learning-Partners nach Land oder Region](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country).


      Mit der Einführung dieses neuen Dienstes begrenzen wir die Anzahl der qualifizierten Lernpartner. Im Laufe des nächsten Jahres werden Lernpartner hinzugefügt, die bestimmte Kriterien erfüllen.
  - question: >
      Ich habe den Supportkanal des Learning-Partners durchsucht und keine Antwort erhalten.
    answer: >-
      Der Lernpartner ist für die Unterstützung bei der Terminplanung auf seiner Website verantwortlich. Sie können verschiedene Nummern für den Lernpartner ausprobieren, indem Sie sich seine Website ansehen.


      Wenn Sie den Learning-Partner noch immer nicht erreichen können, stellen Sie Ihre Frage im [Learn-Supportforum zu Präsenzschulungen von Learning-Partnern](https://trainingsupport.microsoft.com/en-us/iltvilt/forum). Dies ist die beste Ressource, um Hilfe zu bitten, ein Problem zu melden und Rat zu erhalten.
